
FROM node:12 as build
WORKDIR app
COPY package*.json /app/
RUN npm install
COPY ./ /app/
RUN npm run build:prod 

FROM nginx
COPY --from=build-stage /app/build/ /usr/share/nginx/html
COPY --from=build-stage /nginx.conf /etc/nginx/conf.d/default.conf

