# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Get Date
        # https://stackoverflow.com/questions/60942067/get-current-date-and-time-in-github-workflows
        run: echo "NOW=$(date +'%Y-%m-%dT%H-%M-%S')" >> $GITHUB_ENV

      - name: User npm ${{matrix.node-version}}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Login to azure container registry
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.DOCKER_REGISTRY }}
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: build Share
        working-directory: ./Share
        run: |
          npm install
          npm test

      # - name: Docker build Web Frontend
      #   working-directory: ./Web
      #   run: |
      #     docker build . -t ${{ secrets.DOCKER_REGISTRY }}/ecad-fun-web
      #     docker tag ${{ secrets.DOCKER_REGISTRY }}/ecad-fun-web ${{ secrets.DOCKER_REGISTRY }}/ecad-fun-web:$NOW
      #     docker image push ${{ secrets.DOCKER_REGISTRY }}/ecad-fun-web

      - name: Docker build Server Backend
        working-directory: ./Server
        run: |
          docker build . -t ${{ secrets.DOCKER_REGISTRY }}/ecad-fun-server
          docker tag ${{ secrets.DOCKER_REGISTRY }}/ecad-fun-server ${{ secrets.DOCKER_REGISTRY }}/ecad-fun-server:$NOW
          docker image push ${{ secrets.DOCKER_REGISTRY }}/ecad-fun-server
        env:
          CI: true

    # - uses: amondnet/vercel-action@v19
    #   with:
    #     vercel-token: ${{ secrets.VERCEL_TOKEN }} # Required
    #     github-token: ${{ secrets.GITHUB_TOKEN }} #Optional
    #     vercel-args: '--prod' #Optional
    #     vercel-org-id: ${{ secrets.ORG_ID}}  #Required
    #     vercel-project-id: ${{ secrets.PROJECT_ID}} #Required
    #     working-directory: ./Web
