# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: ecad-fun

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: User npm ${{matrix.node-version}}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
          
      - name: Change to frontend directory
        working-directory: ./Web
        run: ls -R
      
      - name: install package
        working-directory: ./Web
        run: npm install
        
      - name: build app
        working-directory: ./Web
        run: npm run build
        env:
          CI: true
        
