# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: build

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: User npm ${{matrix.node-version}}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}


      - name: build MultiPlayer
          working-directory: ./MultiPlayer
          run: |
            npm install
            npm build

      - name: build Web Frontend
        working-directory: ./Web
        run: |
          ls
          ls node_modules
          npm install
          npm run build
        env:
          CI: true

      # - uses: amondnet/vercel-action@v19
      #   with:
      #     vercel-token: ${{ secrets.VERCEL_TOKEN }} # Required
      #     github-token: ${{ secrets.GITHUB_TOKEN }} #Optional
      #     vercel-args: '--prod' #Optional
      #     vercel-org-id: ${{ secrets.ORG_ID}}  #Required
      #     vercel-project-id: ${{ secrets.PROJECT_ID}} #Required
      #     working-directory: ./Web
